version: '3'
services:
  web:
    volumes:
      - $PWD/redirect_80.template:/etc/nginx/conf.d/redirect.template
    build: .
    image: http80_302:latest
    ports: 
    # should match NGINX_PORT on the right side
      - "80:80"
    restart: unless-stopped
    environment:
      - NGINX_HOST=<your_hostname_here>
      - NGINX_PORT=<your_listener_port_here>
    command: /bin/ash -c "envsubst '$$NGINX_PORT $$NGINX_HOST' < /etc/nginx/conf.d/redirect.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
